classes.bard = {
	"Flavour": `A bard is the life of the party.  Her music keeps her friends alert and alive, focusses them in battle, and refreshes them when they are weary.`,
	"Stats": {
		"str": false,
		"dex": true,
		"con": false,
		"cha": true,
		"int": true,
		"wis": true,
		"hit die": 8,
	},
	"All": [
		"Reaching level 1, 5, 9, 13, and 17 in this class grants or improves the Melee Weapons skill or the Ranged Weapons skill.",
	],
	"Level 1": [
		"Potent Music - Bards empower their allies and hamper their enemies through music.  As an action, you may begin to Play a Song which you then magically sustain, or you can continue to Play it, building on it by adding one Chord to the Song.  When you take damage, you must make a Wisdom save with DC equal to the damage taken or lose one Chord.  When you start a Song, it begins with one Chord, and a Song ends when you lose all of a Song's Chords or you have not spent an action to Play it for 5 rounds.  You may start up to two new Songs every hour, but if you start a Song when you are already playing a Song, the Chords transfer to the new Song.  You can have at most 3 Chords at a time.  Playing a Song provokes attacks of opportunity.  You must use an instrument properly to Play a Song.\nIf you are capable of it, you may cast spells while sustaining a Song, but you may not continue sustaining a Song if you must also concentrate on a spell.",
		"Extra Attack (Lesser) - You may attack additional times when you use your standard action to attack. The number of attacks you can make is dependent on your total levels in classes with Extra Attack. At 8 levels you can make two attacks total and at 16 you can make three.",
		"Bardic Training - Choose a Song.",
	],
	"Songs": [
		"Song of Rest - Allies within 30 feet gain one hit point per round per Chord.  If an allied creature listens to the song for at least 15 minutes, they regain uses of their abilities as though they had rested for one hour.  Potent Music is not affected by Song of Rest.",
		"Discordant Whispers - All enemies within 30 feet recieve Disadvantage on all of their saving throws.",
		"Notes of Nettle - Enemies lose one hit point per Chord when they start their turn within 30 feet or move within 30 feet for the first time on their turn.  This damage does not deal wounds.",
		"Cutting Chime - Enemies within 30 feet lose hit points equal to your Chords whenever they are hit by one of your allies' attacks. This damage does not deal wounds.",
		"Sapping Symphony - Enemies within 30 feet have their Constitution score decreased by the number of Chords you have for the purpose of calculating how many wounds they take. This does not decrease a creature's effective Constitution score below half of its original value.",
		"Melody of Mana - Allies within 30 feet gain 1 additional mana each time they channel and 1 additional Ki point each time they Meditate.",
		"Aria of Alacrity - Allies within 30 feet gain 5 movement speed per Chord you have.  This Song gains an additional Chord each time you Play (including the first time - when you begin Playing it).",
		"Echo of Armour - This Song imposes Disadvantage on the first attack made against each of your allies within 30 feet each round.  If you have at least 3 Chords, a second attack is affected and if you have at least 5 Chords, a third attack is affected.  This applies to each of your allies separately (each ally should track the effect on themselves).",
		"Martyr's Cry - When an ally within 30 feet is wounded, you may choose to recieve all of the wounds from that attack instead.  If you do, your ally suffers none of the effects he would have suffered from the attack which caused the wound (beyond the damage recieved).  For instance, if he would have taken extra damage because of the wound or had to make a save against an effect, neither of you take that extra damage or make a save.",
		"Crescendo of Competence - Allies within 30 feet gain a bonus equal to your Chords when attempting a skill check of your choice.  You declare what skill this Song will benefit when you begin Playing it.",
		"Tune of Temerity - Allies within 30 feet gain Advantage on all saving throws.",
	],
	"Bard": [
		"Harmony - You may have two additional Chords at a time. You may choose this feature any number of times, but the total bonus you get from Harmony cannot exceed your Charisma modifier.",
		"Encore - The number of Songs you can start every hour is increased by your Intelligence modifier minus one (minimum +1).",
		"Dynamics - When you Play a song, you may play louder, increasing its effective range to 45 feet but granting Advantage to enemies on checks relating to whether they can hear it.  Alternately, you may play half as loud, decreasing its range to 15 feet and imposing Disadvantage to enemies on checks relating to whether they can hear it.",
		"Tempo - Gain half of your current Chords as AC, rounded up.",
		"Sostenudo - You now only need to Play your Songs once every 10 rounds for them to not end.",
		"Accent - When you Play a song, you may make a single attack with a weapon you hold in one hand. If it hits, gain one Chord.",
	],
	"General": [
		"Echo - You may gain Advantage on a skill check if you see another creature succeed at it first.  The successful attempt must have been in the last 10 minutes, and you must have seen the successful attempt more recently than your most recent attempt.",
		"Charm - By playing music, telling stories, or otherwise entertaining people, you may reroll any social check made by yourself or a nearby party member, using your modifiers instead of theirs.  Your party member must agree to have you roll, but if they do they must use your result even if it is worse.",
		"Witty Riposte - If you didn't attack on your last turn, you may use your reaction to deal damage equal to your Charisma modifier plus your Chords (if any) to a creature when it misses you with a melee attack.",
		"Expertise - Gain a rank in a skill. Ranks in that skill now grant you +3 on relevant skill checks. You may gain this feature more than once.",
	],
};