classes.monk = {
	"Stats": {
		"str": true,
		"dex": true,
		"con": false,
		"cha": true,
		"int": true,
		"wis": false,
		"hit die": 10,
	},
	"All": [
		"Unarmed Prowess - Your base unarmed damage die size increases by two (d4 -> d6 -> d8 -> d10 -> d12) at Monk level  1, 4, 7, 10, 13, 16, and 19.  If your unarmed damage die is already a d12, instead gain +1 damage on all of your unarmed attacks.",
		"Unarmoured Defense - While wearing no armour, gain a bonus to your AC equal to half of your Monk level (rounded up).  You lose this bonus any time you would be denied your Dexterity bonus to AC, even if your Dexterity modifier is 0 or lower.",
		"Reaching level 1, 5, 9, 13, and 17 in this class grants or improves the Unarmed Combat skill.",
	],
	"Level 1": [
		"Ki - You have a pool of Ki you can use to power your abilities.  Your maximum Ki is equal to your level plus your Intelligence modifier.  Gain the Ki Strike technique.  Techniques may be activated more than once per round, but their effects do not stack with themselves.",
		"Extra Attack (Lesser) - You may attack additional times when you use your standard action to attack. The number of attacks you can make is dependent on your total levels in classes with Extra Attack. At 8 levels you can make two attacks total and at 16 you can make three.",
		"Meditate - You can meditate, taking no actions (including reactions) for one round and regaining one Ki point.",
	],
	"Ki Techniques": [
		"Ki Strike - Spend one Ki point to deal an additional 1d6+Cha damage on all of your attacks until the start of your next turn.  You may activate this technique after you hit.",
		"Stunning Strike - Spend one Ki point when you hit with an attack to force the target to make a Constitution save with DC equal to 10 plus your Charisma modifier.  On a failed save, that creature is stunned until the end of your next turn.  Either way, it is immune to Stunning Strike until the end of your next turn.",
		"Hundred League Step - Spend one Ki point to move a distance up to your speed as a swift action.  Attacks of opportunity made against you as a result of this movement are at Disadvantage. During this movement you may ignore difficult terrain.",
		"Phantom Fist - Once per attack, spend one Ki point to reroll one to-hit die or all of your damage dice. You must use the new result.",
		"Retributive Strike - Immediately after being wounded, spend one Ki point to make an attack against the creature that wounded you as a reaction.  If the attack does damage, it deals one additional wound.",
		"Steel Skin - When you take damage, spend one Ki point as a free action to suffer one fewer wound.  If this causes you to not be wounded from the attack, you also lose no hit points.",
		"Flurry of Blows - Spend one Ki point to attack one additional time this turn.",
		"Harness Elements: Air - Spend one Ki point to increase your reach by 5 feet until the end of your turn.",
		"Harness Elements: Fire - Spend one Ki point to increase your critical threat range by 1 until the end of your turn (normally, this changes critical strikes to happen on 19-20 rather than just 20).  If you score a critical hit, deal an additional 2d6 fire damage.",
		"Harness Elements: Water - Spend one Ki point to move to a space within your reach without provoking attacks of opportunity whenever you hit a creature with an attack before the beginning of your next turn.  The creature you hit must remain within your reach.",
		"Harness Elements: Earth - Spend one Ki point to increase your AC by 2 until the beginning of your next turn.  You may use this technique as a reaction to being attacked.",
		"Master Elements - Spend one Ki point to activate two of your Harness Elements techniques (instead of their normal cost).",
		"Cloud Step - Spend one Ki point to not fall until the beginning of your next turn.  If you jump, you may jump a second time at the apex of your jump (but you may not jump off of the air more than once per activation of Cloud Step).  Alternately, you can fall but take no fall damage. You may activate this technique as a reaction any time you would fall.",
		"Wound Soul - Spend a Ki point when you hit a creature with an attack to force it to immediately make a death saving throw with Disadvantage.",
		"Disrupt Mana - When a creature within your reach attempts to channel, you may spend a Ki point to make an attack of opportunity as a reaction.  If it hits, that creature must make a Wisdom save with DC equal to 5 plus the damage done or lose the mana gained from the channel.",
		"Soul Shield - When you would be affected by a spell, you may prevent it from affecting you as a reaction.  You lose Ki points equal to half of the mana spent to cast the spell (rounded up).  If you don't have enough Ki points, you take one wound for each Ki point you are missing.  You may use this technique even if you don't have any Ki points.",
	],
	"Monk": [
		"Combat Meditation - When you meditate, you can still defend yourself.  Attackers have Disadvantage when attacking you while you are meditating.",
		"Centred - You gain two additional Ki points when you meditate.",
		"Bodily Integrity - You are immune to non-magical disease.  You gain Advantage on saves against the effects of poison and saves against magical diseases.",
		"Perfect Form - When you take a long rest, you heal half (rounded down) of your wounds.  For example, if you had 7 wounds, you would heal half (3) plus the one you would normally heal, and have only 3 wounds in the morning.",
		"Efficient Meridians - Each round, the third Ki point you spend is refunded. For the purpose of Efficient Meridians, rounds are considered to begin at the start of your turn.",
	],
	"General": [
		"Fast Movement - Your speed increases by 10 feet.  You gain a +2 bonus on skill checks that involve movement.",
		"Tumble - You may tumble, avoiding opportunity attacks from any creature that did not threaten you at the start of your turn.  If you use this feature, you cannot move both before and after any other action this turn.",
		"Whole Body a Weapon - You may use an unarmed strike as an offhand weapon, even if both of your hands are full.",
		"Improved Initiative - You gain a +2 bonus to initiative.  You retain your Dexterity bonus to AC when you are surprised.",
		"Deflect Arrows - Once per round, when you would be hit by an arrow or other projectile weighing fewer pounds than your strength modifier (minimum 1), you may knock it out of the air as a free action and take no damage.  You cannot deflect critical hits.",
		"Quick Reflexes - When you make a successful physical save against an attack or effect which normally deals half damage on a successful save, take no damage instead.",
		"Evasion - When you fail a physical save against an attack or effect which normally deals half damage on a successful save, take half damage anyway.",
		"Saving Throws: Change - Gain +3 on your Change Saving Throws (Strength and Charisma).",
	],
};