classes.monk = {
	"Stats": {
		"str": true,
		"dex": true,
		"con": true,
		"cha": true,
		"int": false,
		"wis": false,
	},
	"All": [
		"Unarmed Prowess - Your unarmed damage die size increases by two (d4 -> d6 -> d8 -> d10 -> d12) at every odd Monk level.  If your unarmed damage die is already a d12, instead gain +1 damage on all of your unarmed attacks.",
		"Unarmoured Defense - While wearing no armour, gain a bonus to your AC equal to half of your Monk level (rounded up).  You lose this bonus any time you would be denied your Dexterity bonus to AC, even if your Dexterity modifier is 0 or lower.",
		"Reaching level 1, 5, 9, 13, and 17 in this class grants or improves the Unarmed Combat skill.",
	],
	"Level 1": [
		"Ki - You have a pool of Ki you can use to power your abilities.  Your maximum Ki is equal to half your level rounded up plus your Wisdom modifier.  Gain the Ki Strike technique.  Techniques may be activated more than once per round, but their effects do not stack with themselves.",
		"Meditate - You can meditate, taking no actions for one round and regaining one Ki point.",
	],
	"Ki Techniques": [
		"Ki Strike - Spend one Ki point to deal an additional 1d6+Wis damage on all of your attacks until the start of your next turn.  You may activate this technique after you hit.",
		"Cloud Step - Spend one Ki point to not fall during or at the end of your turn.  If you jump, you may jump a second time at the apex of your jump.  Alternately, you can fall but take no fall damage.",
		"Stunning Strike - Spend one Ki point when you hit with an attack to force the target to make a Fortitude save with DC equal to 10 plus your Wisdom modifier.  On a failed save, that creature is stunned until the end of your next turn.  Either way, it is immune to Stunning Strike until the end of your next turn.",
		"Hundred League Step - Spend one Ki point to move a distance up to your speed as a swift action.  Attacks of opportunity made against you as a result of this movement are at Disadvantage.",
		"Phantom Fist - Once per attack, spend one Ki point to reroll one to-hit die or all of your damage dice.",
		"Retributive Strike - Immediately after being wounded, spend one Ki point to make an attack against the creature that wounded you as a reaction.  If the attack does damage, it deals one additional wound.",
		"Steel Skin - When you take damage, spend one Ki point to suffer one fewer wound.  If this causes you to not be wounded from the attack, you also lose no hit points.",
		"Flurry of Blows - Spend one Ki point to attack one additional time this turn.",
		"Harness Elements (Air) - Spend one Ki point to increase your reach by 5 feet until the end of your turn.",
		"Harness Elements (Fire) - Spend one Ki point to increase your critical threat range by 1 until the end of your turn (normally, this changes critical strikes to happen on 19-20 rather than just 20).  If you score a critical hit, deal an additional 2d6 fire damage.",
		"Harness Elements (Water) - Spend one Ki point to move 5 feet without provoking attacks of opportunity whenever you hit a creature with an attack before the beginning of your next turn.  The creature you hit must remain within your reach.",
		"Harness Elements (Earth) - Spend one Ki point to increase your AC by 2 until the beginning of your next turn.  You may use this technique as a reaction to being attacked.",
		"Master Elements - Spend one Ki point to activate any number of your Harness Elements techniques.",
		"Wound Soul - Spend a Ki point when you hit a creature with an attack to force it to immediately make a death saving throw with Disadvantage.",
		"Disrupt Mana - When a creature within your reach attempts to channel, you may make an attack of opportunity.  If it hits, that creature must make a Wisdom save with DC equal to 5 plus the damage done or lose the mana gained from the channel.",
		"Soul Shield - When you would be affected by a spell, you may prevent it from affecting you as a reaction.  You lose Ki points equal to half of the mana spent to cast the spell (rounded up).  If you don't have enough Ki points, you take one wound for each Ki point you are missing.  You may use this technique even if you don't have any Ki points.",
	],
	"Monk": [
		"Combat Meditation - When you meditate, you can still defend yourself.  Attackers have Disadvantage when attacking you while you are meditating.",
		"Centred - You gain two additional Ki points when you meditate.",
		"Bodily Integrity - You are immune to disease.  You gain Advantage against the secondary effects of poison.",
		"Perfect Form - When you take a long rest, you heal half (rounded down) of your wounds.  For example, if you had 7 wounds, you would heal half (3) plus the one you would normally heal, and have only 3 wounds in the morning.",
		"Efficient Meridians - Each round, the third Ki point you spend is refunded.",
	],
	"General": [
		"Fast Movement - Your speed increases by 10 feet.  You gain a +2 bonus to checks made to move like climbing, swimming, or jumping.",
		"Tumble - You don't provoke opportunity attacks when leaving a space threatened by a creature unless that creature threatened you at the start of your turn and it no longer threatens you.",
		"Whole Body a Weapon - You may use an unarmed strike as an offhand weapon, even if both of your hands are full.",
		"Improved Initiative - You gain a +2 bonus to initiative.  You retain your Dexterity bonus to AC when you are surprised.",
		"Deflect Arrows - Once per round, when you are hit by an arrow or other projectile weighing fewer pounds than your strength modifier (minimum 1), you may knock it out of the air and take no damage.  You cannot deflect critical hits.",
		"Quick Reflexes - When you make a successful physical save against an attack or effect which normally deals half damage on a successful save, take no damage instead.",
		"Evasion - When you fail a physical save against an attack or effect which normally deals half damage on a successful save, take half damage anyway.",
	],
};
