classes.rogue = {
	"Stats": {
		"str": true,
		"dex": true,
		"con": true,
		"cha": false,
		"int": false,
		"wis": true,
		"hit die": 6,
	},
	"All": [
		"Martial weapon proficiency",
		"Reaching level 1, 5, 9, 13, and 17 in this class grants or improves the Melee Weapons skill or the Ranged Weapons skill.",
	],
	"Level 1": [
		"Precision - When you have Advantage on an attack and the lower die would hit, the attack deals one extra wound.  Creatures immune to critical hits are also immune to these wounds.",
		"Extra Attack (Greater) - You may attack additional times when you use your standard action to attack. The number of attacks you can make is dependent on your total levels in classes with Extra Attack. At 6 levels, you can make two attacks total. At 12 you can make three and at 18 you can make four attacks.",
	],
	"Rogue": [
		"Good Aim - When you have Advantage on an attack, add 5 to the lower die before determining which die to take.  This cannot result in a roll greater than 20 and does not cause critical threats if the original value would not be a critical threat.",
		"Lethal Strike - Whenever you deal a wound to a creature with Precision, that creature must make a death saving throw or fall unconscious as if it had taken two or more wounds.  The creature has a malus on this save equal to your total Advantage on the attack.",
		"Accuracy - When you do not have any Advantage on an attack, you gain Advantage.  This does not allow you to use any feature which you can only use if you have Advantage.",
		"Deadly - Your attacks deal 2 additional damage.  You may choose this feature any number of times, but the total bonus you receive from it may not exceed your Dexterity modifier.",
	],
	"General": [
		"Hidden Blade - When you miss an attack against a creature who does not know your location, you may immediately attempt a skill check to hide as a free action.",
		"Slip Away - When an ally hits an adjacent enemy with an attack, you may use a reaction to move up to 10 feet without provoking an attack of opportunity from the hit creature.",
		"Combat Reflexes (Rogue) - You may take additional reactions each round up to your Dexterity modifier (minimum 1 extra reaction).  Each extra reaction may only be used to activate a Rogue feature, and you may only react to any given event once.",
		"Slippery - When an enemy misses you with an attack, you may use a reaction to impose Disadvantage on attacks they make against you before the end of your next turn.",
		"Twist the Knife - When an adjacent enemy is hit by an attack, you may use a reaction to increase the damage dealt by that attack by 2.",
		"Quick Reflexes - When you make a successful physical save against an attack or effect which normally deals half damage on a successful save, take no damage instead.",
		"Evasion - When you fail a physical save against an attack or effect which normally deals half damage on a successful save, take half damage anyway.",
		"Improved Initiative - You gain a +2 bonus to initiative.  You retain your Dexterity bonus to AC when you are surprised.",
		"Constant Threat - If you would have Advantage on an attack, you may choose not to roll to hit and just do damage as though you had hit.  If you do, that damage cannot cause the target to take any wounds.",
		"Feint - As a swift action, you may gain Advantage on your next attack before the beginning of your next turn.  If you Feint multiple times, you gain Advantage on multiple attacks (it does not grant multiple Advantages on one attack).",
		"Cunning - You may move your speed or attempt a skill check (like hiding, pickpocketing, or picking a lock) which would usually require a standard action as a swift action.",
		"Expertise - Gain a rank in a skill. Ranks in that skill now grant you +3 on relevant skill checks. You may gain this feature more than once.",
		"Saving Throws: Physical - Gain +1 on your Physical Saving Throws (Strength, Dexterity, and Constitution).",
	],
};