const SPELL_TYPES = {
	// Damage types
	Fire: "Fire",
	Cold: "Cold",
	Lightning: "Lightning",
	Acid: "Acid",
	Sonic: "Sonic",
	Psionic: "Psionic",
	Radiant: "Radiant",
	Force: "Force",
	Positive: "Positive Energy",
	Negative: "Negative Energy",

	Sustained: "Sustained",
}

const DAMAGE = {
	Acid: "1d8 acid damage",
	Cold: "1d8 cold damage",
	Fire: "2d6 fire damage",
	Force: "1d6 force damage",
	Lightning: "1d10 lightning damage",
	Negative: "1d10 negative energy damage",
	Positive: "1d10 positive energy damage",
	Psionic: "1d10 psionic damage",
	Radiant: "1d8 radiant damage",
	Sonic: "1d8 sonic damage",
}

const EFFECT = {
	Acid: "Creatures adjacent to creatures damaged by acid take 1d4 acid damage.",
	Cold: "Creatures who fail their save are Slowed for 1 round.",
	Fire: "",
	Force: "Force spells do not permit saves.",
	Lightning: "Saves made by creatures wearing metal armour have Disadvantage.",
	Negative: "Undead creatures are healed by negative energy.",
	Positive: "Living creatures are healed by positive energy.",
	Psionic: "Wounds dealt by psionic damage do not reduce the amount of damage dealt to hit points.",
	Radiant: "Creatures who fail their save are Blinded for 1 round.",
	Sonic: "Creatures who fail their save are Deafened for 1 round.",
}

const STATUSES = {
	Blind: "A Blind creature is unable to see using its eyes.  If it has no other way of detecting creatures, it get -A against creatures within its reach and -2A against creatures whose locations are known but are outside of its reach.",
	Deaf: "A Deaf creature is unable to hear.  Unless it is trained in sign language, it cannot communicate during combat unless a creature spends an action to communicate something simple.  Additionally, creatures flanking it get their flanking bonus increased to +2A.",
	Slowed: "A Slowed creature spends 1 additional foot of movement for every foot it travels.",
}

const SOURCES = {
	Arcane: "Arcane",
	Divine: "Divine",
	Psionic: "Psionic",
}

const SCHOOLS = {
	Abjuration: "Abjuration",
	Conjuration: "Conjuration",
	Divination: "Divination",
	Enchantment: "Enchantment",
	Evocation: "Evocation",
	Illusion: "Illusion",
	Necromancy: "Necromancy",
	Transmutation: "Transmutation",
	Universal: "Universal",
}

const SAVES = {
	Strength: "Strength",
	Dexterity: "Dexterity",
	Constitution: "Constitution",
	Wisdom: "Wisdom",
	Intelligence: "Intelligence",
	Charisma: "Charisma",
	None: "None",
}

const RANGE = {
	Self: "Self",
	Touch: "Touch",
	Short: "25 feet",
	Medium: "50 feet",
	Long: "100 feet",
	Far: "250 feet",
}

const DURATIONS = {
	Minute: "1 minute",
	Hour: "1 hour",
}

const UPKEEP = {
	Half: "Half of the initial mana cost",
	One: "One mana",
}

let spells = [
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Fire],
	name: "Fireball",
	requirements: [],
	effect: `You create a small bead that flies out to the target location and explodes. The explosion deals ${DAMAGE.Fire} to each creature within 10 feet, or half that much on a successful dexterity save.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Fire} and its radius increases by 5 feet.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Fire],
	name: "Wall of Fire",
	requirements: ["Fireball"],
	effect: `You sweep out an arc with your arm, and a straight 30 foot long wall of fire springs up.  Vision through the wall is completely blocked.  Creatures who begin their turn in the wall or enter it take ${DAMAGE.Fire}.  Creatures in the wall when it first appears who succeed on a dexterity save may move 5 feet as a reaction.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Fire} and its length increases by 5 feet.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Fire],
	name: "",
	requirements: ["Fireball"],
	effect: "",
	manaEffect: "",
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Cold],
	name: "Ray of Frost",
	requirements: [],
	effect: `A line of ice emanates out from you, freezing everything in its path.  Creatures caught in the ray take ${DAMAGE.Cold}, or half that much on a successful constitution save.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Cold}.`,
	spellData: {
		range: RANGE.Long,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Cold],
	name: "Glaciate",
	requirements: ["Ray of Frost"],
	effect: `The ground around you freezes, keeping your enemies from reaching you.  Creatures within 20 feet must make a constitution save or be unable to leave their space for one round and take ${DAMAGE.Cold}.  Creatures who succeed on their save take half damage.  The area becomes difficult terrain until it warms up (naturally, or by someone casting a fire spell in that space).  You are unaffected by the ice this turn.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Cold}.`,
	spellData: {
		range: RANGE.Self,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Cold],
	name: "",
	requirements: ["Ray of Frost"],
	effect: "",
	manaEffect: "",
	spellData: {
		range: RANGE.Self,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Lightning],
	name: "Chain Lightning",
	requirements: [],
	effect: `Lightning arcs from your fingers to another creature.  The target takes ${DAMAGE.Lightning}.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Lightning} and jumps to an additional creature.  Each extra target must be within ${RANGE.Short} of the previous target.`,
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Lightning],
	name: "Capacitate",
	requirements: ["Chain Lightning"],
	effect: `You touch a surface and charge it with electricity.  Starting at the end of your next turn, the next time a creature comes within 5 feet of the point you touch, all creatures within 5 feet of the trap or another target take ${DAMAGE.Lightning}, or half that on a successful dexterity save.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Lightning} and you may increase the range of activation by 5 feet or the rage of detonation by 5 feet.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Lightning, SPELL_TYPES.Sustained],
	name: "Lightning Plague",
	requirements: ["Chain Lightning"],
	effect: `You point at a creature and it contracts the lightning plague unless it succeeds on a ${SAVES.Constitution} save.  If it contracts the lightning plague, then at the beginning of each of its turns, creatures within ${RANGE.Short} of it must make a ${SAVES.Constitution} save or contract the lightning plague, and then it may attempt a ${SAVES.Constitution} to end this effect.  Creatures who contract the lightning plague take ${DAMAGE.Lightning} at the start of each of their turns.  A creature may not contract the lightning plague if it has already been affected by the same casting of the spell, and you may specify any number of creatures to be immune when you cast the spell.  Those creatures (including yourself) are only immune so long as you sustain the channel.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Lightning} each turn.`,
	spellData: {
		range: RANGE.Short,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		duration: DURATIONS.Minute,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Sonic],
	name: "Shout",
	requirements: [],
	effect: `You create a loud sound which deafens your enemies.  Creatures in a 45 degree cone take ${DAMAGE.Sonic}.  If they fail their save, they are also deafened until the start of your next turn.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Sonic} and the save DC increases by 1.`,
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Sonic],
	name: "",
	requirements: ["Shout"],
	effect: ``,
	manaEffect: ``,
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Sonic],
	name: "",
	requirements: ["Shout"],
	effect: ``,
	manaEffect: ``,
	spellData: {
		range: RANGE.Short,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Force],
	name: "Magic Missile",
	requirements: [],
	effect: `You launch an unerring missile of pure force that homes in on your adversary.  It deals ${DAMAGE.Force}.`,
	manaEffect: `For each additional mana used, fire an additional missile.  It can target the same creature or a different creature.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Force],
	name: "",
	requirements: ["Magic Missile"],
	effect: "",
	manaEffect: "",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Force],
	name: "",
	requirements: ["Magic Missile"],
	effect: "",
	manaEffect: "",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Acid],
	name: "",
	requirements: [],
	effect: "",
	manaEffect: "",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Radiant],
	name: "Flare",
	requirements: [],
	effect: `You create a bright light above your head.  Creatures other than you within ${RANGE.Medium} who can see you take ${DAMAGE.Radiant}, or half that on a successful save.  Creatures who fail the save are blinded for one round.  Creatures may take the Ready action to close their eyes and automatically succeed on the save.`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Radiant}.`,
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Radiant],
	name: "Sunbeam",
	requirements: ["Flare"],
	effect: `You create a 15 foot radius pillar of light.  Creatures who start their turn in the pillar or who enter it for the first time on their turn take ${DAMAGE.Radiant}, or half that on a successful save.  Creatures who fail the save are blinded for one round.  Only you can see into, out of, or through the pillar.`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Radiant}.`,
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Radiant],
	name: "",
	requirements: [],
	effect: "",
	manaEffect: "",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive],
	name: "Cure Wounds",
	requirements: [],
	effect: "You channel positive energy into an adjacent creature.  It heals one wound.  If positive energy damages the target, you must succeed on a touch attack or the spell is wasted (and the spell deals one wound instead).",
	manaEffect: "For each two additional mana used, the healing increases by one wound.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive, SPELL_TYPES.Sustained],
	name: "Aura of Life",
	requirements: ["Cure Wounds"],
	effect: "You channel positive energy into the space around you.  Creatures within 15 feet of you take 2d6 positive energy damage (this is healing to living creatures).  Creatures which enter the range of the spell before the start of your next turn also suffer the damage (only once per creature).  The aura only affects you if you wish it to.",
	manaEffect: "For each additional mana used, the healing increases by 1d6.  The mana cost to maintain the spell is equal to half of the initial cost, rounded up.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		upkeep: UPKEEP.Half,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive, SPELL_TYPES.Sustained],
	name: "Regeneration",
	requirements: ["Cure Wounds"],
	effect: "You touch an allied creature and its wounds begin to close.  At the beginning of each of its turns, the target is healed of one wound.",
	manaEffect: "For each additional 2 mana used, the target heals one additional wound each turn.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive],
	name: "Resurrection",
	requirements: ["Cure Wounds"],
	effect: "This spell restores life to one creature that died within the past day.  The creature's soul must be willing to return, and it could not have died from old age.  As long as the creature's body is mostly intact, the spell restores it.  Otherwise, the creature returns to life with overdraw wounds equal to its constitution score.  In any case, resurrection imposes a significant strain on the creature's body and soul, and it permanently loses one point from a random ability score.",
	manaEffect: "For each additional mana used, the amount of time that the creature could have been dead increases by 1 day.",
	spellData: {
		range: RANGE.Touch,
		minMana: 6,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative],
	name: "Inflict Wounds",
	requirements: [],
	effect: "You channel negative energy into an adjacent creature.  If you succees on a touch attack, it suffers one wound.  If negative energy heals the target, it instead regains one wound.",
	manaEffect: "For each two additional mana used, the damage increases by one wound.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative, SPELL_TYPES.Sustained],
	name: "Aura of Death",
	requirements: ["Inflict Wounds"],
	effect: "You channel negative energy into the space around you.  Creatures within 15 feet of you take 2d6 negative energy damage.  Creatures which enter the range of the spell before the start of your next turn also suffer the damage (only once per creature).  The aura only affects you if you wish it to.",
	manaEffect: "For each additional mana used, the damage increases by 1d6.  The mana cost to maintain the spell is equal to half of the initial cost, rounded up.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		upkeep: UPKEEP.Half,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative, SPELL_TYPES.Sustained],
	name: "Wither",
	requirements: ["Inflict Wounds"],
	effect: "You touch a creature and wounds begin to open.  At the beginning of each of its turns, the target suffers one wound unless it succeeds on a constitution save.",
	manaEffect: "For each additional 2 mana used, the target suffers one additional wound each turn.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Conjuration,
		save: SAVES.Constitution,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative],
	name: "Animate Dead",
	requirements: ["Inflict Wounds"],
	effect: "You touch a corpse, and it comes to life under your control.  It follows your commands, but it cannot carry out complex actions.  Each dawn, you must expend one of your channels or allow the creature to collapse.  It is capable of using the weapons it carried in life as well as its natural weapons.",
	manaEffect: `Additional mana allows you to give more complex commands.  The DM will adjudicate whether the command is possible.  Some representative commands:
+0: Follow me; kill them
+1: Collect the weapons in that room
+2: Guard a door, killing anyone who doesn't present a particular symbol
+3: Search a building, killing any inhabitants
+4: Retrieve a book in a library with a particular name`,
	spellData: {
		range: RANGE.Touch,
		minMana: 6,
		school: SCHOOLS.Necromancy,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Psionic],
	descriptors: [],
	name: "Counterspell",
	requirements: [],
	effect: "Target creature casting a spell must make an Intelligence save or have that spell's effective mana cost reduced by the amount of mana spent on this spell.  If the resultant effective mana cost is less than the minimum for the spell, the spell has no effect.  This spell may be cast as a reaction to seeing a creature cast a spell.",
	manaEffect: `Additional mana spent on the spell increases the reduction of the effective mana cost of the spell being cast by the target creature.`,
	spellData: {
		range: RANGE.Long,
		minMana: 1,
		school: SCHOOLS.Universal,
		save: SAVES.None,
	},
},

];