spells = [
...spells,
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Resistance",
	requirements: [],
	effect: "You touch a creature and grant it a measure of protection. It gains +1 to all of its saving throws.",
	manaEffect: "Each additional mana improves the bonus by +1.",
	spellData: {
		range: RANGE.Touch,
		minMana: 1,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Resiliance",
	requirements: [],
	effect: "You touch a creature and grant it a measure of protection. After taking a Wound it regains 3 hit points (this can occur multiple times in a single attack).",
	manaEffect: "Each additional mana used increases the effect by 1.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Elemental Adaptation",
	requirements: [],
	effect: "Choose an element. The creature you touch gains resistance 1 against that element (including against the effect of high temperature if the element chosen is Fire, low temperature if the element chosen is Cold, or other analogous effects for other elements).",
	manaEffect: "For each additional mana, the resistance is increased by 1 and the duration is doubled.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Hold Portal",
	requirements: [],
	effect: "Target gate, door, window, or other entryway is held shut by a great force. The DC required to open it increases by 5 (to a minimum of 15). A portal or empty doorframe is held shut by an invisible force (DC 10 to cross).",
	manaEffect: "Each additional mana used increases the DC by 2.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Day,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Protection From Chaos/Evil/Good/Law",
	requirements: [],
	effect: "When you cast this spell, choose an alignment. The warded creature gains Advantage against effects created by creatures of the chosen alignment, and creatures of the chosen alignment have Disadvantage on attacks against the warded creature. Spells and abilities of creatures of the chosen alignment which possess or otherwise control the warded creature are suppressed for the duration.",
	manaEffect: "For each two additional mana used, you may target one additional creature and the duration increases by 1 minute.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Circle Against Chaos/Evil/Good/Law",
	requirements: ["Protection From Chaos/Evil/Good/Law"],
	effect: "When you cast this spell, choose an alignment. You create a 10 foot radius circle which creatures of the chosen alignment cannot cross. The spell immediately ends if the circle of salt used to create the spell is disturbed. Creatures of the chosen alignment cannot disturb the circle, even indirectly, but other creatures can. Attacks and spells which pass into or out of the circle grant the effects of Protection From Evil to their targets (modified to the appropriate alignment). Creatures of the chosen alignment are unable to plane shift, teleport, or otherwise escape the circle without the caster of such a spell succeeding on a Charisma save.",
	manaEffect: "For every 3 additional mana used, you may choose an additional alignment it protects against.",
	spellData: {
		range: RANGE.Touch,
		minMana: 4,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Dawn,
		castTime: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Shield",
	requirements: [],
	effect: "You conjure an invisible magical shield interposed between yourself and an incoming attack. It grants you +2 AC against that attack and any other attack before the beginning of your next turn. You may cast this spell as a reaction to being hit by an attack, before you know how much damage you take.",
	manaEffect: "For each additional mana used, increase the bonus AC by 2.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Sphere of Denial",
	requirements: ["Shield"],
	effect: "You conjure an arcane sphere around yourself with a radius of 5 feet.  Any attack or damaging spell targetted at you, another creature within the sphere, or a point within the sphere by a creature outside of the sphere instead hits the sphere.  Once the sphere has taken 50 damage, it collapses (but the attack which breaks it does not deal damage to creatures inside).",
	manaEffect: "For each additional mana used, increase the hit points of the sphere by 50.",
	spellData: {
		range: RANGE.Self,
		minMana: 4,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Invulnerability",
	requirements: ["Shield"],
	effect: "You become immune to all damage for the duration of this spell.",
	manaEffect: "For each additional mana used, increase the duration by 1 minute.",
	spellData: {
		range: RANGE.Self,
		minMana: 9,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Alarm",
	requirements: [],
	effect: "You ward a 30 foot square area against entry. The next time a Tiny or larger creature enters the warded area, you hear a chime that instantly wakes you from sleep. You may specify a password that, if spoken by any creature near the alarmed area, disables the Alarm for one round.",
	manaEffect: "",
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Dawn,
		castTime: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Trap",
	requirements: ["Alarm"],
	effect: "You ward a 30 foot square area against entry. The next time a Tiny or larger creature enters the warded area, you hear a chime that instantly wakes you from sleep. You may specify a password that, if spoken by any creature near the trapped area, disables the Trap for one round.",
	manaEffect: "As a part of casting this spell, cast a second spell which can target a single creature, for which you must pay double the mana cost (add the total to this spell's cost). That spell is cast upon the creature who triggers the trap.",
	spellData: {
		range: RANGE.Short,
		minMana: 0,
		school: SCHOOLS.Abjuration,
		save: SAVES.None,
		duration: DURATIONS.Dawn,
		castTime: DURATIONS.Minute,
	},
},
];