spells = [
...spells,
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive],
	name: "Cure Wounds",
	requirements: [],
	effect: "You channel positive energy into an adjacent creature.  It heals one wound.  If positive energy damages the target, you must succeed on a touch attack or the spell is wasted (and the spell deals one wound instead).",
	manaEffect: "For each two additional mana used, the healing increases by one wound.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive, SPELL_TYPES.Sustained],
	name: "Regeneration",
	requirements: ["Cure Wounds"],
	effect: "You touch an allied creature and its wounds begin to close.  At the beginning of each of its turns, the target is healed of one wound.",
	manaEffect: "For each two additional mana used, the target heals one additional wound each turn.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive],
	name: "Resurrection",
	requirements: ["Cure Wounds"],
	effect: "This spell restores life to one creature that died within the past day.  The creature's soul must be willing to return, and it could not have died from old age.  As long as the creature's body is mostly intact, the spell restores it.  Otherwise, the creature returns to life with overdraw wounds equal to its constitution score, but with body reconstituted by the spell.  In any case, resurrection imposes a significant strain on the creature's body and soul, and it permanently loses one point from a random ability score.",
	manaEffect: "For each additional mana used, the amount of time that the creature could have been dead increases by 1 day.",
	spellData: {
		range: RANGE.Touch,
		minMana: 6,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative],
	name: "Inflict Wounds",
	requirements: [],
	effect: "You channel negative energy into an adjacent creature.  If you succeed on a touch attack, it suffers one wound.  If negative energy heals the target, it instead heals one wound.",
	manaEffect: "For each two additional mana used, the damage increases by one wound.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative, SPELL_TYPES.Sustained],
	name: "Wither",
	requirements: ["Inflict Wounds"],
	effect: "You touch a creature and wounds begin to open on them.  At the beginning of each of its turns, the target suffers one wound unless it succeeds on a constitution save.",
	manaEffect: "For each two additional mana used, the target suffers one additional wound each turn.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Conjuration,
		save: SAVES.Constitution,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Mage Armour",
	requirements: [],
	effect: `One creature gains +2 AC for the duration of the spell. Each time the creature is damaged, the bonus granted is reduced by 1. The spell ends early when the bonus is reduced to 0.`,
	manaEffect: `Each additional mana spent increases the initial bonus by 1.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Fog",
	requirements: [],
	effect: `Fog billows out from a point you designate into a 20 foot tall, 20 foot radius cloud. All vision beyond 5 feet is obscured, and all attacks are made with Disadvantage. Wind dissipates Fog in 1 to 4 rounds, depending on the speed and strength of the wind.`,
	manaEffect: `Each additional mana spent increases the radius and height by 10 feet.`,
	spellData: {
		range: RANGE.Long,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Solid Fog",
	requirements: ["Fog"],
	effect: `Functions like Fog, but it is so thick that all creatures within have their speed reduced to 5 feet. Melee attacks are made at an additional Disadvantage, and ranged attacks are impossible. Only a strong wind dissipates Solid Fog (in 1 round).`,
	manaEffect: `Each additional mana spent increases the radius and height by 10 feet.`,
	spellData: {
		range: RANGE.Long,
		minMana: 3,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Acid],
	name: "Acid Fog",
	requirements: ["Fog", "Acid Splash"],
	effect: `Functions like Fog, but any creature that enters it or starts their turn in it takes ${DAMAGE.Acid} from the caustic vapors.`,
	manaEffect: `Each additional mana increases the radius and height by 10 feet and does an extra ${DAMAGE.Acid}.`,
	spellData: {
		range: RANGE.Long,
		minMana: 4,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Acid],
	name: "Acid Splash",
	requirements: [],
	effect: `Conjure an orb of acid, and hurl it at a creature within range. Make a ranged attack against the creature (using Charisma as the key ability). If you hit, deal ${DAMAGE.Acid}.`,
	manaEffect: `Each additional mana spent increases the damage dealt by ${DAMAGE.Acid}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Acid],
	name: "Caustic Arrow",
	requirements: ["Acid Splash"],
	effect: `Conjure an arrow of acid, and fire it at a creature within range. Make a ranged attack against the target (with Charisma as the key ability). If you hit, deal ${DAMAGE.Acid} each round for the duration.`,
	manaEffect: `Each additional mana spent increases the duration by one round.`,
	spellData: {
		range: RANGE.Long,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Round,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Grease",
	requirements: [],
	effect: `Magical grease coats the ground in a 10 foot square you indicate.  Creatures within the area must save or fall prone at the start of their turn or when they begin moving within the area.  The area is also difficult terrain.  Alternately, you may Grease a single object, which then cannot be held without a successful save.  If the object is being held by a creature, the creature may make a Wisdom save to prevent the spell from taking effect.`,
	manaEffect: `Each additional mana spent increases the size of the square greased by 5 feet.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.Dexterity,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Create Tool",
	requirements: [],
	effect: `You cause a small object to appear in your hand.  It can be made of any mundane material (except for gold or a higher metal like mithril or adamantium) and possesses normal traits (it can't be overly hot, cold, or caustic).  It can be whatever shape you need, and up to 5 feet long in one dimension, with a maximum cross section of 5 square feet.  When the duration is over, it vanishes.`,
	manaEffect: `Each additional mana spent doubles the duration.`,
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Phantom Steed",
	requirements: [],
	effect: `You summon a phantasmal steed.  It has 18 AC, 50 hit points, and a speed of 100 feet.  It obeys its rider, but can only be ridden by the one person you created it for.  It can bear its rider's weight plus the weight of the rider's gear, plus 100 pounds.  It cannot attack, but animals fear it and will not attack it.`,
	manaEffect: `Each additional mana spent increases the Phantom Steed's speed by 50 feet and its maximum hit points by 10.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 3,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Create Material",
	requirements: [],
	effect: `You create a small amount of a substance.  It cannot have any extreme properties (including heat, cold, acidity, or hardness) and it appears very roughly in a shape you specify.  If you create water, it is potable but not pure.  You can create wood or stone, but not processed materials like paper or metal.  You create up to 1 cubic foot of material.  If it is a solid, it must be resting on a surface that can support it or in your hand.`,
	manaEffect: `Each additional mana spent doubles the total amount made.`,
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine, SOURCES.Primal, SOURCES.Arcane],
	descriptors: [],
	name: "Light",
	requirements: [],
	effect: `You touch a small object and it begins to emit light.  The light can point in one direction, in all directions, or anything in between (a cone, for instance).  The light illuminates areas of Darkness cast with less mana (if the two spells are of equal strength, the first-cast one takes effect).  The light illuminates an area out to 20 feet (and the same distance of dim light beyond that).`,
	manaEffect: `Each additional mana spent increases the radius of the light by 20 feet.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Divine, SOURCES.Primal, SOURCES.Arcane],
	descriptors: [],
	name: "Darkness",
	requirements: [],
	effect: `You touch a small object and it begins to radiate shadowy darkness out to a 20 foot radius.  Natural light is incapable of brighting the area, as are Light and Radiant spells cast with less mana (if the two spells are of equal strength, the first-cast one takes effect).  Creatures with infravision cannot see in magical darkness.  Covering the object that Darkness was cast on also blocks the darkness.`,
	manaEffect: `Each additional mana spent increases the radius of the darkness by 20 feet.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
];