spells = [
...spells,
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive],
	name: "Cure Wounds",
	requirements: [],
	effect: "You channel positive energy into an adjacent creature.  It heals one wound.  If positive energy damages the target, you must succeed on a touch attack or the spell is wasted (and the spell deals one wound instead).",
	manaEffect: "For each two additional mana used, the healing increases by one wound.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive, SPELL_TYPES.Sustained],
	name: "Regeneration",
	requirements: ["Cure Wounds"],
	effect: "You touch an allied creature and its wounds begin to close.  At the beginning of each of its turns, the target is healed of one wound.",
	manaEffect: "For each additional 2 mana used, the target heals one additional wound each turn.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive],
	name: "Resurrection",
	requirements: ["Cure Wounds"],
	effect: "This spell restores life to one creature that died within the past day.  The creature's soul must be willing to return, and it could not have died from old age.  As long as the creature's body is mostly intact, the spell restores it.  Otherwise, the creature returns to life with overdraw wounds equal to its constitution score.  In any case, resurrection imposes a significant strain on the creature's body and soul, and it permanently loses one point from a random ability score.",
	manaEffect: "For each additional mana used, the amount of time that the creature could have been dead increases by 1 day.",
	spellData: {
		range: RANGE.Touch,
		minMana: 6,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative],
	name: "Inflict Wounds",
	requirements: [],
	effect: "You channel negative energy into an adjacent creature.  If you succees on a touch attack, it suffers one wound.  If negative energy heals the target, it instead regains one wound.",
	manaEffect: "For each two additional mana used, the damage increases by one wound.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative, SPELL_TYPES.Sustained],
	name: "Wither",
	requirements: ["Inflict Wounds"],
	effect: "You touch a creature and wounds begin to open.  At the beginning of each of its turns, the target suffers one wound unless it succeeds on a constitution save.",
	manaEffect: "For each additional 2 mana used, the target suffers one additional wound each turn.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Conjuration,
		save: SAVES.Constitution,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Mage Armour",
	requirements: [],
	effect: `One creature gains +2 AC for the duration of the spell. Each time the creature is damaged, the bonus granted is reduced by 1. The spell ends when the bonus is reduced to 0 or one hour has passed.`,
	manaEffect: `Each additional mana spent increases the initial bonus by 1.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Fog",
	requirements: [],
	effect: `Fog billows out from a point you designate into a 20 foot tall, 20 foot radius cloud. All vision beyond 5 feet is obscured, and all attacks are made with Disadvantage. Wind dissipates Fog in 1 to 4 rounds, depending on the speed strength of the wind.`,
	manaEffect: `Each additional mana spent increases the radius by 10 feet.`,
	spellData: {
		range: RANGE.Long,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Solid Fog",
	requirements: ["Fog"],
	effect: `Functions like Fog, but it is so thick that all creatures within have their speed reduced to 5 feet. Melee attacks are made at an additional Disadvantage, and ranged attacks are impossible. Only a strong wind dissipates Solid Fog (in 1 round).`,
	manaEffect: `Each additional mana spent increases the radius by 10 feet.`,
	spellData: {
		range: RANGE.Long,
		minMana: 3,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Acid Fog",
	requirements: ["Fog", "Acid Splash"],
	effect: `Functions like Fog, but any creature that enters it or starts their turn in it takes ${DAMAGE.Acid} from the caustic vapors.`,
	manaEffect: `Each additional mana increases the radius by 10 feet and does an extra ${DAMAGE.Acid}.`,
	spellData: {
		range: RANGE.Long,
		minMana: 4,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Acid Splash",
	requirements: [],
	effect: `Conjure an orb of acid, and hurl it at a creature within range. Make a ranged attack against the creature (using Charisma as the key ability). If you hit, deal ${DAMAGE.Acid}.`,
	manaEffect: `Each additional mana spent increases the damage dealt by ${DAMAGE.Acid}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Caustic Arrow",
	requirements: ["Acid Splash"],
	effect: `Conjure an arrow of acid, and fire it at a creature within range. Make a ranged attack against the target (with Charisma as the key ability). If you hit, deal ${DAMAGE.Acid}.`,
	manaEffect: `Each additional mana spent increases the duration by one round.`,
	spellData: {
		range: RANGE.Long,
		minMana: 1,
		school: SCHOOLS.Conjuration,
		save: SAVES.None,
		duration: DURATIONS.Round,
	},
},
];