spells = [
...spells,
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Foresight",
	requirements: [],
	effect: "You catch a glimpse of the near future. You may spend the glimpse to gain Advantage on one roll of your choice before the end of your next turn.",
	manaEffect: "For each additional mana you spend, you may delay your use of the glimpse by up to one round.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [],
	name: "Augury",
	requirements: [],
	effect: "You ask your god about a course of action you intend to take within the next hour. Your god replies <i>Weal</i> if that action would have good results, <i>Woe</i> if it would have negative results, but does not reply if the future is sufficiently unclear. Augury fails if you have already attempted an Augury today. Augury does not guarantee a result, but your DM should not attempt to mislead you with this spell.",
	manaEffect: "For each additional mana you spend, you may have already cast Augury once today.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Clairvoyance",
	requirements: [],
	effect: "You create an invisible eye in a location you are familiar with or can describe accurately. You see through the eye as though you were there. You may reorient it and move it up to 5 feet in any direction on your turn as a standard action.\nIf you also have clairaudience, you may cast both spells as a single spell with the same target for 3 mana.",
	manaEffect: "Each additional mana doubles the range or doubles the duration.",
	spellData: {
		range: RANGE.Distant,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Clairaudiance",
	requirements: [],
	effect: "You create an invisible ear in a location you are familiar with or can describe accurately. You hear through the ear as though you were there. You may reorient it and move it up to 5 feet in any direction on your turn as a standard action.\nIf you also have clairvoyance, you may cast both spells as a single spell with the same target for 3 mana.",
	manaEffect: "Each additional mana doubles the range or doubles the duration.",
	spellData: {
		range: RANGE.Distant,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Detect Magic",
	requirements: [],
	effect: "You detect magical auras. Each round that you maintain this spell you identify which objects or creatures within range are magical or have ongoing magical effects.",
	manaEffect: "Spending one additional mana reveals the school of one aura of your choice per turn.",
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Comprehend Languages",
	requirements: [],
	effect: "For the duration of this spell, you understand what is meant by speech or writing in any language. This does not decipher codes, and it takes focussed effort by you and at least one other creature to uncover the meaning of particular words or symbols rather than the whole sentence.",
	manaEffect: "Each additional mana spent doubles the duration.",
	spellData: {
		range: RANGE.Self,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Detect Thoughts",
	requirements: [],
	effect: "You detect surface thoughts in a circle around you. You know how many intelligent creatures and how many beasts are within range, but this spell does not locate them for you unless you can see them (hidden creatures remain hidden).\nAs an action on your turn, you may attempt to read the surface thoughts of one creature. That creature makes a Wisdom save. If it succeeds, it is notified that something attempted to read its thoughts and you may not attempt to read its mind again with this casting of Detect Thoughts. Otherwise, you learn its surface thoughts.",
	manaEffect: "",
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Truesight",
	requirements: [],
	effect: "You grant the creature touched the ability to see things as they really are. It immediately identifies and sees past illusions, it can see invisible creatures and objects, and sees the true form of polymorphed or transmuted objects and creatures. The truesight reaches out to 25 feet.\nTruesight does not assist with seeing through mundane disguises, spotting hidden creatures, or even through fog or other obscurment.",
	manaEffect: "Each additional mana doubles the duration and the range of the effect.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Guide",
	requirements: [],
	effect: "Touch a creature and grant it an unerring sense of where its enemies are. The affected creature has no miss chance and always targets the right square to hit the enemy it wishes to hit. Guide confers no benefit to hit. No creature within line of sight is considered hidden to the affected creature.",
	manaEffect: "Each additional mana doubles the duration.",
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
];