spells = [
...spells,
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Foresight",
	requirements: [],
	effect: "You catch a glimpse of the near future. You may spend the glimpse to gain Advantage on one roll of your choice before the end of your next turn.",
	manaEffect: "For each additional mana you spend, you may delay your use of the glimpse by up to one round.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [],
	name: "Augury",
	requirements: [],
	effect: "You ask your god about a course of action you intend to take within the next hour. Your god replies <i>Weal</i> if that action would have good results, <i>Woe</i> if it would have negative results, but does not reply if the future is sufficiently unclear. Augury fails if you have already attempted an Augury today. Augury does not guarantee a result, but your DM should not attempt to mislead you with this spell.",
	manaEffect: "For each additional mana you spend, you may have already cast Augury once today.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Clairvoyance",
	requirements: [],
	effect: "You create an invisible eye in a location you are familiar with or can describe accurately. You see through the eye as though you were there. You may reorient it and move it up to 5 feet in any direction on your turn as a standard action.\nIf you also have clairaudience, you may cast both spells as a single spell with the same target for 3 mana.",
	manaEffect: "Each additional mana doubles the range or doubles the duration.",
	spellData: {
		range: RANGE.Distant,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Clairaudiance",
	requirements: [],
	effect: "You create an invisible ear in a location you are familiar with or can describe accurately. You hear through the ear as though you were there. You may reorient it and move it up to 5 feet in any direction on your turn as a standard action.\nIf you also have clairvoyance, you may cast both spells as a single spell with the same target for 3 mana.",
	manaEffect: "Each additional mana doubles the range or doubles the duration.",
	spellData: {
		range: RANGE.Distant,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Detect Magic",
	requirements: [],
	effect: "You detect magical auras. Each round that you maintain this spell you identify which objects or creatures within range are magical or have ongoing magical effects.",
	manaEffect: "Spending one additional mana reveals the school of one aura of your choice per turn.",
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Comprehend Languages",
	requirements: [],
	effect: "For the duration of this spell, you understand what is meant by speech or writing in any language. This does not decipher codes, and it takes focussed effort by you and at least one other creature to uncover the meaning of particular words or symbols rather than the whole sentence.",
	manaEffect: "Each additional mana spent doubles the duration.",
	spellData: {
		range: RANGE.Self,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Detect Thoughts",
	requirements: [],
	effect: "You detect surface thoughts in a circle around you. You know how many intelligent creatures and how many beasts are within range, but this spell does not locate them for you unless you can see them (hidden creatures remain hidden).\nAs an action on your turn, you may attempt to read the surface thoughts of one creature. That creature makes a Wisdom save. If it succeeds, it is notified that something attempted to read its thoughts and you may not attempt to read its mind again with this casting of Detect Thoughts. Otherwise, you learn its surface thoughts.",
	manaEffect: "",
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Truesight",
	requirements: [],
	effect: "You grant the creature touched the ability to see things as they really are. It immediately identifies and sees past illusions, it can see invisible creatures and objects, and sees the true form of polymorphed or transmuted objects and creatures. The truesight reaches out to 25 feet.\nTruesight does not assist with seeing through mundane disguises, spotting hidden creatures, or even through fog or other obscurment.",
	manaEffect: "Each additional mana doubles the duration and the range of the effect.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Guide",
	requirements: [],
	effect: "Touch a creature and grant it an unerring sense of where its enemies are. The affected creature has no miss chance and always targets the right square to hit the enemy it wishes to hit. Guide confers no benefit to hit. No creature within line of sight is considered hidden to the affected creature if the creature is aware of their presence.",
	manaEffect: "Each additional mana spent doubles the duration.",
	spellData: {
		range: RANGE.Touch,
		minMana: 3,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Foretell",
	requirements: [],
	effect: "You take a glimpse into the near future, determining the result of something you're about to do before you do it.  Choose an action that you plan to do before the beginning of your next turn that requires a d20 roll by you.  Roll 1d20.  If you perform the action before the beginning of your next turn, use the roll as one of your d20 rolls for that action (if you have Advantage or Disadvantage, you still need to roll the other die).  You may cast this spell as a swift action.",
	manaEffect: "For each additional mana you spend, you may modify the result by 1 up or down (but not above 20 or below 1).",
	spellData: {
		range: RANGE.Self,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Locate Object",
	requirements: [],
	effect: "You sense the location of an object known to you.  You may target either a particular object you have observed in person or a general class of object, in which case the spell guides you toward the nearest one.",
	manaEffect: "Each additional mana doubles the range and duration of the effect.",
	spellData: {
		range: RANGE.Long,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Locate Creature",
	requirements: [],
	effect: "You sense the location of an creature known to you.  You may target either a particular creature you have observed in person or a type of creature, in which case the spell guides you toward the nearest one.  The spell is blocked by running water.",
	manaEffect: "Each additional mana doubles the range and duration of the effect.",
	spellData: {
		range: RANGE.Long,
		minMana: 3,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Tongues",
	requirements: [],
	effect: "When you speak, your words come out in a intelligible to one creature that you choose, and speech in that language is intelligible to you.  The language chosen is random among the languages that the creature speaks.  You may suspend the effect at will.  If the creature does not speak a language, only it understands you when you speak.",
	manaEffect: "Each additional mana doubles the duration of the effect.",
	spellData: {
		range: RANGE.Self,
		minMana: 2,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "True Speech",
	requirements: [],
	effect: "When you speak, your words are intelligible to all creatures who hear, provided that those creatures speak any language.  You may not whisper or shout.",
	manaEffect: "Each additional mana doubles the duration of the effect.",
	spellData: {
		range: RANGE.Self,
		minMana: 3,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Detect Scrying",
	requirements: [],
	effect: "You immediately become aware of any divination spells which reveal you or your words.",
	manaEffect: "If you spend another 2 mana, you also become aware of where the caster of the spell is, in general terms.",
	spellData: {
		range: RANGE.Self,
		minMana: 4,
		school: SCHOOLS.Divination,
		save: SAVES.None,
		duration: DURATIONS.Dawn,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Scrying",
	requirements: [],
	effect: "You focus on a creature.  If it fails its save, its image appears in a crystal ball, pool of water, or puff of smoke.  Through it you can see 10 feet of its surroundings in every direction and hear noises as if you were there.  The creature has Advantage on the save if you do not know it well.",
	manaEffect: "Each additional mana doubles the duration of the effect.",
	spellData: {
		range: RANGE.Touch,
		minMana: 5,
		school: SCHOOLS.Divination,
		save: SAVES.Wisdom,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Doom",
	requirements: [],
	effect: "Roll 1d20.  Then choose a creature and audibly specify an action that it may take in the future.  When that creature takes the action you specify, you may substitute the roll that you made for one of the dice that it rolls.",
	manaEffect: "For each additional mana spent, you may modify the roll by up to 2 (but not below 1 or above 20)",
	spellData: {
		range: RANGE.Short,
		minMana: 4,
		school: SCHOOLS.Divination,
		save: SAVES.Wisdom,
		duration: DURATIONS.Dawn,
	},
},
];