spells = [
...spells,
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Sleep",
	requirements: [],
	effect: `You say some soft words and you cause any number of targets to fall asleep.  For each target beyond the first, each target gains Advantage on the saving throw.  If the creature is in combat or is doing a strenuous activity, it gains Advantage on the saving throw.  Those creatures wake up immediately if they take any damage or an adjacent creature spends their action to waken them.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Charm Person",
	requirements: [],
	effect: `This charm makes a humanoid regard you as a friend.  If the target is currently being threatened or attacked by you or your allies, it recieves Advantage on the saving throw.  It does not do whatever you say, but interprets your words in the most favourable light.  You or your allies attacking the charmed person breaks the spell.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Hideous Laughter",
	requirements: [],
	effect: `The target creature is afflicted with uncontrollable laughter.  It can take no actions and falls prone.  It can attempt the save again at the end of each of its turns and whenever it is Wounded.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Hold Person",
	requirements: [],
	effect: `You hold a humanoid with magical bonds, preventing them from moving. The creature is incapacitated for the duration or until Wounded.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [],
	name: "Hold Monster",
	requirements: ["Hold Person"],
	effect: `You hold a creature with magical bonds, preventing it from moving. The creature is incapacitated for the duration or until Wounded.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 6,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Heroism",
	requirements: [],
	effect: `You inspire a creature to greater deeds.  That creature gains Advantage on skill checks and saving throws.`,
	manaEffect: "If you spend an additional 2 mana, it also gains Advantage on attacks.",
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Enchantment,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Suggestion",
	requirements: ["Charm Person"],
	effect: `You suggest a course of action to a creature, and compel it to do so.  The creature attempts to carry out that action, but it will not do anything obviously harmful (if it is obviously harmful, the spell breaks).`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 4,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Dawn,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Charm Monster",
	requirements: ["Charm Person"],
	effect: `This charm makes a living creature regard you as a friend.  If the target is currently being threatened or attacked by you or your allies, it recieves Advantage on the saving throw.  It does not do whatever you say, but interprets your words in the most favourable light.  You or your allies attacking the charmed creature breaks the spell.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Medium,
		minMana: 4,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Geas",
	requirements: [],
	effect: `You compel a creature to your service.  You give it orders, and it must carry them out.  A Geas cannot compel a creature to kill itself or face certain death.  Each day that the creature does not attempt to follow your instructions, it recieves 1 Overdraw Wound.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 7,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Month,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.MindAffecting],
	name: "Crushing Despair",
	requirements: [],
	effect: `You manipulate the minds of creatures in a 90 degree cone.  Each creature within the cone is overcome by despair and get Disadvantage on skill checks and saving throws.`,
	manaEffect: "For each additional mana spent, increase the spell's DC by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 5,
		school: SCHOOLS.Enchantment,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
];