spells = [
...spells,
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Fire],
	name: "Fireball",
	requirements: [],
	effect: `You create a small bead that flies out to the target location and explodes. The explosion deals ${DAMAGE.Fire} to each creature within 5 feet.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Fire} and its radius increases by 5 feet.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Fire],
	name: "Wall of Fire",
	requirements: ["Fireball"],
	effect: `You sweep out an arc with your arm, and a straight 30 foot long, 15 foot tall wall of fire springs up.  Vision through the wall is completely blocked.  Creatures who begin their turn in the wall or enter it take ${DAMAGE.Fire}.  Creatures in the wall when it first appears who succeed on a dexterity save may move 5 feet as a reaction.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Fire} and its length increases by 5 feet.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Fire, SPELL_TYPES.Sustained],
	name: "Inferno",
	requirements: ["Fireball"],
	effect: `Choose a point within range.  A fiery sphere appears in that space.  Creatures who begin their turn within 5 feet of it or come within 5 feet of it for the first time this turn take ${DAMAGE.Fire}.  At the beginning of each turn that you sustain this spell, you may choose another point to create a fiery sphere.  All fiery spheres remain until you stop sustaining the spell.`,
	manaEffect: `For each additional mana used, you may create one additional fiery sphere with the initial cast and each sphere deals an additional ${DAMAGE.Fire}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 4,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Cold],
	name: "Ray of Frost",
	requirements: [],
	effect: `A line of ice emanates out from you, freezing everything in its path.  Creatures caught in the ray take ${DAMAGE.Cold}.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Cold}.`,
	spellData: {
		range: RANGE.Long,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Cold],
	name: "Glaciate",
	requirements: ["Ray of Frost"],
	effect: `The ground around you freezes, keeping your enemies from reaching you.  Creatures within 20 feet are unable to leave their space for one round and take ${DAMAGE.Cold}.  The area becomes difficult terrain until it warms up (naturally, or by someone casting a fire spell in that space).  You are unaffected by the ice this turn.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Cold}.`,
	spellData: {
		range: RANGE.Self,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Cold],
	name: "Chill Orb",
	requirements: ["Ray of Frost"],
	effect: `You create an orb of pure cold and it flies to a target location.  Creatures within 10 feet take ${DAMAGE.Cold} damage.  Creatures that enter the 10 foot radius must repeat the save or take the damage.  Creatures who spend their whole turn within the radius take the damage and are not permitted a save.
	A creature may pick up the orb and throw it or attempt to hit it away.  When hit with an object, the orb moves 2d10+STR feet.  When thrown, the orb deals its damage to the thrower and the target (if it hits).`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Cold}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Lightning],
	name: "Chain Lightning",
	requirements: [],
	effect: `Lightning arcs from your fingers to another creature.  The target takes ${DAMAGE.Lightning}.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Lightning} and jumps to an additional creature.  Each extra target must be within ${RANGE.Short} of the previous target.`,
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Lightning],
	name: "Capacitate",
	requirements: ["Chain Lightning"],
	effect: `You touch a surface and charge it with electricity.  Starting at the end of your next turn, the next time a creature comes within 5 feet of the point you touch, all creatures within 5 feet of the trap or the target take ${DAMAGE.Lightning}.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Lightning} and you may increase the range of activation by 5 feet or the rage of detonation by 5 feet.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
		duration: DURATIONS.Hour,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Lightning, SPELL_TYPES.Sustained],
	name: "Lightning Plague",
	requirements: ["Chain Lightning"],
	effect: `You point at a creature and it contracts the lightning plague.  If it contracts the lightning plague, then at the beginning of each of its turns, creatures within ${RANGE.Short} of it must make a ${SAVES.Constitution} save or contract the lightning plague, and then it may attempt a ${SAVES.Constitution} to end this effect.  Creatures who contract the lightning plague take ${DAMAGE.Lightning} at the start of each of their turns.  A creature may not contract the lightning plague if it has already been affected by the same casting of the spell, and you may specify any number of creatures to be immune when you cast the spell.  Those creatures (including yourself) are only immune so long as you sustain the channel.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Lightning} each turn.`,
	spellData: {
		range: RANGE.Short,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		duration: DURATIONS.Minute,
		upkeep: UPKEEP.One,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Sonic],
	name: "Shout",
	requirements: [],
	effect: `You create a loud sound which deafens your enemies.  Creatures in a 45 degree cone take ${DAMAGE.Sonic}.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Sonic} and the save DC increases by 1.`,
	spellData: {
		range: RANGE.Short,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Sonic],
	name: "Thunderwave",
	requirements: ["Shout"],
	effect: `Thunder booms, throwing creatures away from you.  Creatures in a 45 degree cone take ${DAMAGE.Sonic}.  Creatures that fail their save are pushed 10 feet away from you and fall prone.`,
	manaEffect: `For each additional 2 mana used, the spell deals an additional ${DAMAGE.Sonic} and the save DC increases by 1.`,
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Sonic],
	name: "Sonic Boom",
	requirements: ["Shout"],
	effect: `Your speed doubles until the end of your turn.  Any creature adjacent to a space that you move out of this turn takes ${DAMAGE.Sonic}.  You may cast this spell as a swift action.`,
	manaEffect: `For each additional mana used, the spell deals an additional ${DAMAGE.Sonic} and your speed increases by 5 (prior to doubling).`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Force],
	name: "Magic Missile",
	requirements: [],
	effect: `You launch an unerring missile of pure force that homes in on your adversary.  It deals ${DAMAGE.Force}.`,
	manaEffect: `For each additional mana used, fire an additional missile.  It can target the same creature or a different creature.`,
	spellData: {
		range: RANGE.Long,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Force],
	name: "Batter",
	requirements: ["Magic Missile"],
	effect: `You fire a rain of tiny balls of force at a creature, interrupting its focus.  It takes ${DAMAGE.Force} (but cannot deal Wounds) and must make a Concentration check with DC equal to your spell save DC.  If it fails the Concentration check it loses any spell it is concentrating on and gets Disadvantage on all of its saving throws until the end of your next turn.`,
	manaEffect: `For each additional mana used, deal an additional ${DAMAGE.Force} and increase the DC on the Concentration save by 1.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 3,
		school: SCHOOLS.Evocation,
		save: SAVES.Dexterity,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [SPELL_TYPES.Radiant],
	name: "Flare",
	requirements: [],
	effect: `You create a bright light above your head.  Creatures other than you within ${RANGE.Medium} who can see you take ${DAMAGE.Radiant}.  Creatures may take the Ready action to close their eyes and automatically succeed on the save.`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Radiant}.`,
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [SPELL_TYPES.Radiant],
	name: "Sunbeam",
	requirements: ["Flare"],
	effect: `You create an 80 foot tall, 15 foot radius pillar of light.  Creatures who start their turn in the pillar or who enter it for the first time on their turn take ${DAMAGE.Radiant}.  Only you can see into, out of, or through the pillar.`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Radiant}.`,
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Positive, SPELL_TYPES.Sustained],
	name: "Aura of Life",
	requirements: ["Cure Wounds"],
	effect: "You channel positive energy into the space around you.  Creatures within 15 feet of you take 2d6 positive energy damage (this is healing to living creatures).  Creatures which enter the range of the spell before the start of your next turn also suffer the damage (only once per creature).  The aura only affects you if you wish it to.",
	manaEffect: "For each additional mana used, the healing increases by 1d6.  The mana cost to maintain the spell is equal to half of the initial cost, rounded up.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		upkeep: UPKEEP.Half,
	},
},
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Negative, SPELL_TYPES.Sustained],
	name: "Aura of Death",
	requirements: ["Inflict Wounds"],
	effect: "You channel negative energy into the space around you.  Creatures within 15 feet of you take 2d6 negative energy damage.  Creatures which enter the range of the spell before the start of your next turn also suffer the damage (only once per creature).  The aura only affects you if you wish it to.",
	manaEffect: "For each additional mana used, the damage increases by 1d6.  The mana cost to maintain the spell is equal to half of the initial cost, rounded up.",
	spellData: {
		range: RANGE.Self,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Constitution,
		upkeep: UPKEEP.Half,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Psionic],
	name: "Figment",
	requirements: [],
	effect: `You project an image of a creature's worst fear into its mind, dealing ${DAMAGE.Psionic}.  Creatures who fail the save are Frightened until the end of their next turn.`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Psionic}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 1,
		school: SCHOOLS.Evocation,
		save: SAVES.Wisdom,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Psionic],
	name: "Unsettle",
	requirements: ["Figment"],
	effect: `Choose a target creature and an action.  The next time within the duration of this spell the creature performs that action, they feel an intense fear and take ${DAMAGE.Psionic}.  Creatures who fail the save must choose a different action (if it's an attack, it could be the same attack against a different creature).`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Psionic}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 2,
		school: SCHOOLS.Evocation,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane],
	descriptors: [SPELL_TYPES.Psionic],
	name: "Lobotomy",
	requirements: ["Figment"],
	effect: `You manipulate a target creature into forgetting all about you.  It takes ${DAMAGE.Psionic} and cannot consciously percieve you for the duration.  Directly interacting with the creature in any way breaks the spell.`,
	manaEffect: `For each additional mana used, this spell deals an additional ${DAMAGE.Psionic}.`,
	spellData: {
		range: RANGE.Medium,
		minMana: 4,
		school: SCHOOLS.Evocation,
		save: SAVES.Wisdom,
		duration: DURATIONS.Minute,
	},
},
];