spells = [
...spells,
{
	type: [SOURCES.Divine],
	descriptors: [SPELL_TYPES.Radiant],
	name: "Blinding Transfiguration",
	requirements: ["Flare"],
	effect: `Your armour or clothes begin to shine, emitting bright light in a 10 foot radius. Whenever you are hit by an attack, your armour flashes a brilliant white. Creatures within 5 feet of you must save or take ${DAMAGE.Radiant} and be blinded for 1 round. Blind creatures are unaffected.`,
	manaEffect: `For each additional mana used, deal an additional ${DAMAGE.Radiant}.`,
	spellData: {
		range: RANGE.Self,
		minMana: 4,
		school: SCHOOLS.Transmutation,
		save: SAVES.Constitution,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Bull's Strength",
	requirements: [],
	effect: "Grant a target creature +2 to Strength for one minute.",
	manaEffect: "Each additional mana spent increases the bonus by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	}
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Cat's Grace",
	requirements: [],
	effect: "Grant a target creature +2 to Dexterity for one minute.",
	manaEffect: "Each additional mana spent increases the bonus by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	}
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Bear's Endurance",
	requirements: [],
	effect: "Grant a target creature +2 to Constitution for one minute.",
	manaEffect: "Each additional mana spent increases the bonus by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	}
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Owl's Wisdom",
	requirements: [],
	effect: "Grant a target creature +2 to Wisdom for one minute.",
	manaEffect: "Each additional mana spent increases the bonus by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	}
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Fox's Cunning",
	requirements: [],
	effect: "Grant a target creature +2 to Intelligence for one minute.",
	manaEffect: "Each additional mana spent increases the bonus by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	}
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Eagle's Splendour",
	requirements: [],
	effect: "Grant a target creature +2 to Charisma for one minute.",
	manaEffect: "Each additional mana spent increases the bonus by 1.",
	spellData: {
		range: RANGE.Short,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	}
},
{
	type: [SOURCES.Divine, SOURCES.Primal],
	descriptors: [],
	name: "Mending",
	requirements: [],
	effect: `You touch a small damaged object and it returns to an undamaged state.  Mending does not create material, so if some is lost you must supply a patch.  Mending cannot restore magic items.  The spell can fix an item weighing one pound or less or a 3-inch square portion of a larger object.`,
	manaEffect: `Each additional mana spent doubles the mass or area of the object that Mending can repair.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 1,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Primal],
	descriptors: [],
	name: "Regrow",
	requirements: [],
	effect: `You touch a small damaged plant and return it to its undamaged state.  Regrow can restore plants shaped like trees up to one foot tall or a 3-inch square area of a larger or differently-shaped plant.  Regrow may only be cast on one plant once a day, as some of the energy for the spell is taken from the plant.`,
	manaEffect: `Each additional mana spent doubles the mass or area of the plant that Regrow can restore.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 0,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
	},
},
{
	type: [SOURCES.Arcane, SOURCES.Divine],
	descriptors: [],
	name: "Magic Weapon",
	requirements: [],
	effect: `You imbue a weapon with power, allowing it to strike harder and more accurately.  For the duration, the weapon grants +1 to hit and +1 damage.  You can't cast this on a natural weapon (including unarmed strikes).`,
	manaEffect: `Each additional mana spent increases the duration by 1 minute and increases the damage bonus by 1.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
{
	type: [SOURCES.Primal],
	descriptors: [],
	name: "Magic Fang",
	requirements: [],
	effect: `You imbue a natural weapon (potentially an unarmed strike) with primal force, allowing it to strike harder and more accurately.  For the duration, the weapon grants +1 to hit and +1 damage.`,
	manaEffect: `Each additional mana spent increases the duration by 1 minute and increases the damage bonus by 1.`,
	spellData: {
		range: RANGE.Touch,
		minMana: 2,
		school: SCHOOLS.Transmutation,
		save: SAVES.None,
		duration: DURATIONS.Minute,
	},
},
];